#!/bin/sh
SCREENSDIR="/home/jeff/Pictures/screenshots"
FILE=`date +%m-%d-%Y-%s`
import $SCREENSDIR/$FILE.jpg
zenity --question --text="Upload to imgur?"
if [ $? -eq 0 ]; then
	URLS=`imgur $SCREENSDIR/$FILE.jpg`
	if [ $? -eq 0 ]; then
		notify-send -t 2000 "imgur upload complete" "awesome"
		chromium-browser $URLS
	elif [ $? -eq 1 ]; then
		notify-send -t 2000 "imgur upload failed" "sadness"
	fi
fi
